version: '3.8'

services:
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/HelpDesk.Api/.env
    ports:
      - '5000:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/helpdesk.db
    volumes:
      - ./backend/data:/app/data

  frontend-app:
    build:
      context: ./helpdesk-frontend
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - backend-api
